/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Imagenes;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class OPN extends javax.swing.JFrame {

    //MIREN ACA NO IGNOREN ESTO//
//esto es para filtrar los archivos en jfile chooser    
    private final FileNameExtensionFilter fil = new FileNameExtensionFilter("pdf", "pdf");

    //esta es la direccion del archivo
    String direccion = null;
    String llegan = null;
    String titulo = null;

    ArrayList<String> nombres = new ArrayList<>();

    public OPN() {
        startRom();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qeqe = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        qeqe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qeqeActionPerformed(evt);
            }
        });

        jButton1.setText("volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(qeqe, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qeqe, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // AQUI ESTA TODO

    private void qeqeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qeqeActionPerformed

        try {

            JFileChooser elegido = (JFileChooser) evt.getSource();
            //el jfile maneja los comandos en strings
            String comando = evt.getActionCommand();

            if (comando != null) {

                System.out.println(" " + comando);

                if (comando.equals("CancelSelection")) {

                    GUI g = new GUI();
                    g.setVisible(true);
                    setVisible(false);

                }

                if (elegido != null) {
                    //este comando pone el filtro del inicio
                    elegido.setFileFilter(fil);
                    //se hace una variable archivo para meter lo que seleccionamos desde la interfaz

                    File Archivoelegido = elegido.getSelectedFile();

                    //aqui ocupe sacar las 3 ultimas letras del nombre del archivo, esto fue así porque ocupaba que fuera un archivo pdf 
                    //pido el nombre del archivo
                    String nombre = Archivoelegido.getName();

                    int f = nombre.length();
                    //aqui saco ya las tres ultimas letras
                    String formato = nombre.substring((f - 3), f);

                    //aqui el if significa  (si comando equals abrir o seleccionar  y si es pdf
                    if (comando.equals(JFileChooser.APPROVE_SELECTION) && "pdf".equals(formato)) {
                        //aqui mete la direccion del archivo
                        direccion = Archivoelegido.getAbsolutePath();
                        titulo = Archivoelegido.getName();
                        boolean dis = disponible(titulo);
                         if(dis==false) {
                          try {
                          downLoadROM();
                          } catch (IOException ex) {
                          Logger.getLogger(OPN.class.getName()).log(Level.SEVERE, null, ex);
                          }
                          
                          GUI g = new GUI();
                          g.setVisible(true);
                          setVisible(false);
                          
                          } else {
                          
                          JOptionPane.showMessageDialog(null, "ese libro ya esta disponible");
                          
                          }
                    }
                }

            }
        } catch (NullPointerException|HeadlessException e) {
        }

    }//GEN-LAST:event_qeqeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        GUI g = new GUI();
        g.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean disponible(String titulo) {
        boolean d = false;

        for (int i = 0; i < nombres.size(); i++) {

            if (titulo.equals(nombres.get(i))) {
               d=true;
                System.out.println("d ="+d);
            }
    
            
        }
        System.out.println("");
        System.out.println("");
        System.out.println("");
        return d;

    }

    public void ejecutar(String direccion) {
        ProcessBuilder p = new ProcessBuilder();

        p.command("cmd.exe", "/c", direccion);

        try {
            p.start();
        } catch (IOException ex) {

        }

    }

    public void upLoadROM() {

        try {
            FileReader lector = new FileReader("ROMprod.txt");
            BufferedReader BR = new BufferedReader(lector);

            llegan = BR.readLine();

        } catch (IOException ex) {
        }

    }

    public void downLoadROM() throws IOException {
        System.out.println("lleeeeega");

        upLoadROM();
        try (
                FileWriter fichero = new FileWriter("ROMprod.txt");
                FileReader lector = new FileReader("ROMprod.txt");
                BufferedReader BR = new BufferedReader(lector);
                BufferedWriter bw = new BufferedWriter(new FileWriter("ROMprod.txt"))) {

            while (BR.readLine() != null) {
                bw.write(" ");
            }
            bw.close();

            // System.out.println(llegan);
            fichero.write(titulo + "♥" + direccion + "♥" + llegan);

            fichero.close();

        }

    }

    public void startRom() {

        String llegan = null;
        try {
            FileReader lector = new FileReader("ROMprod.txt");
            BufferedReader BR = new BufferedReader(lector);
            llegan = BR.readLine();

        } catch (IOException ex) {
        }

         if (llegan != null) {
        String[] partes;
        partes = llegan.split("♥");
        //System.out.println(llegan);

        

            for (int k = 0; k < partes.length - 1; k += 2) {
                nombres.add(partes[k]);

            }

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPN.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPN.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPN.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPN.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OPN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser qeqe;
    // End of variables declaration//GEN-END:variables
}
